# paper_trading/positions.py
"""
Position management for hermetic paper trading.

Evaluates tick-by-tick stop loss, take profit (inclusive of exact level),
horizon deadlines, gaps, MAE/MFE tracking, and kill switches.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from common.signal_direction import SignalSide
from paper_trading.contracts import ClosedTrade, PaperPosition
from paper_trading.cost_model import CostModel, PnLBreakdown


@dataclass(frozen=True)
class PositionConfig:
    """Configuration for position tracking and exit evaluation."""

    gap_tolerance_ms: int = 60_000
    horizon_grace_ms: int = 10_000
    tp_is_maker: bool = False  # default taker (conservative)


class PositionManager:
    """
    Tracks open simulated positions and evaluates exit conditions on market ticks.

    All tick evaluations execute in memory in O(active_positions) with zero I/O
    and zero tick logging to satisfy hot-path performance requirements.
    """

    def __init__(
        self,
        cost_model: Optional[CostModel] = None,
        config: Optional[PositionConfig] = None,
    ) -> None:
        self.cost_model = cost_model or CostModel()
        self.config = config or PositionConfig()
        self.open_positions: Dict[str, PaperPosition] = {}
        # Composite lookup key: (cohort_id, decision_provider, symbol) -> position_id
        self._cohort_symbol_map: Dict[Tuple[str, str, str], str] = {}
        self._kill_switch_active: bool = False
        self._kill_switch_reason: str = "KILL_SWITCH"

    def has_open_position(self, cohort_id: str, decision_provider: str, symbol: str) -> bool:
        """Check if an open position exists for the given cohort, provider and symbol."""
        key = (cohort_id, decision_provider, symbol)
        return key in self._cohort_symbol_map

    def get_position(self, position_id: str) -> Optional[PaperPosition]:
        """Retrieve open position by id."""
        return self.open_positions.get(position_id)

    def add_position(self, position: PaperPosition) -> None:
        """Register a newly filled position."""
        self.open_positions[position.position_id] = position
        key = (position.cohort_id, position.decision_provider, position.symbol)
        self._cohort_symbol_map[key] = position.position_id

    def close_all(self, reason: str = "KILL_SWITCH") -> None:
        """Activate kill switch to immediately close all positions on the next tick."""
        self._kill_switch_active = True
        self._kill_switch_reason = reason

    def on_tick(
        self,
        T: int,
        p: float,
        q: float,
        m: bool,
        trade_id: int | str = 0,
    ) -> List[ClosedTrade]:
        """
        Process a single market tick against all active positions.

        Strictly O(open_positions), zero disk/DB I/O, zero per-tick logging.
        Returns closed trades generated by this tick.
        """
        closed_trades: List[ClosedTrade] = []
        if not self.open_positions:
            return closed_trades

        # First evaluate grace period timeouts before processing tick
        expired = self.check_expired_positions(T)
        closed_trades.extend(expired)

        # Check remaining positions against incoming tick
        pos_to_remove: List[str] = []

        for pos_id, pos in list(self.open_positions.items()):
            # Position exit evaluation only starts on subsequent ticks (T > opened_ts_ms)
            if T <= pos.opened_ts_ms:
                continue

            pos.ticks_processed += 1

            # Detect data gap between consecutive ticks (or since position opened)
            reference_ts = pos.last_tick_ts_ms if pos.last_tick_ts_ms > 0 else pos.opened_ts_ms
            if (T - reference_ts) > self.config.gap_tolerance_ms:
                pos.data_gap = True
            pos.last_tick_ts_ms = T

            # Update MAE / MFE in bps
            self._update_mae_mfe(pos, p)

            # Check for kill switch
            if self._kill_switch_active:
                closed = self._close_trade_at_market(
                    pos=pos,
                    exit_reason="KILL_SWITCH",
                    raw_exit_price=p,
                    exit_ts_ms=T,
                )
                closed_trades.append(closed)
                pos_to_remove.append(pos_id)
                continue

            # Check exit conditions chronologically
            closed_trade = self._evaluate_tick_exit(pos, T, p)
            if closed_trade is not None:
                closed_trades.append(closed_trade)
                pos_to_remove.append(pos_id)

        # Remove closed positions from state
        for pos_id in pos_to_remove:
            self._remove_position(pos_id)

        if self._kill_switch_active and not self.open_positions:
            self._kill_switch_active = False

        return closed_trades

    def check_expired_positions(self, current_ts_ms: int) -> List[ClosedTrade]:
        """
        Check for positions that have received no tick past their horizon + grace period.

        Generates UNKNOWN_DATA_GAP trades with None PnL.
        """
        expired_trades: List[ClosedTrade] = []
        pos_to_remove: List[str] = []

        for pos_id, pos in self.open_positions.items():
            cutoff = pos.horizon_deadline_ms + self.config.horizon_grace_ms
            if current_ts_ms >= cutoff:
                fees_bps = (pos.entry_fee_usdt / pos.notional_usdt * 10_000.0) if pos.notional_usdt > 0 else 0.0
                slip_bps = (pos.entry_slippage_usdt / pos.notional_usdt * 10_000.0) if pos.notional_usdt > 0 else 0.0

                closed = ClosedTrade(
                    trade_id=f"tr_{pos.position_id}",
                    decision_id=pos.decision_id,
                    cohort_id=pos.cohort_id,
                    decision_provider=pos.decision_provider,
                    symbol=pos.symbol,
                    side=pos.side,
                    entry_price=pos.entry_price,
                    exit_price=pos.entry_price,
                    quantity=pos.quantity,
                    notional_usdt=pos.notional_usdt,
                    opened_ts_ms=pos.opened_ts_ms,
                    closed_ts_ms=current_ts_ms,
                    exit_reason="UNKNOWN_DATA_GAP",
                    trade_direction_profitable=None,
                    prediction_direction_correct=None,
                    trade_win=None,
                    gross_pnl_bps=None,
                    net_pnl_bps=None,
                    fees_bps=fees_bps,
                    slippage_bps=slip_bps,
                    funding_bps=None,
                    gross_pnl_usdt=None,
                    fees_usdt=pos.entry_fee_usdt,
                    slippage_usdt=pos.entry_slippage_usdt,
                    funding_usdt=None,
                    net_pnl_usdt=None,
                    pnl_R=None,
                    costs_complete=False,
                    data_gap=True,
                    mae_bps=pos.mae_bps,
                    mfe_bps=pos.mfe_bps,
                    ticks_count=pos.ticks_processed,
                    direction_correct=None,
                    context=pos.context,
                )
                expired_trades.append(closed)
                pos_to_remove.append(pos_id)

        for pos_id in pos_to_remove:
            self._remove_position(pos_id)

        return expired_trades

    def _remove_position(self, position_id: str) -> None:
        pos = self.open_positions.pop(position_id, None)
        if pos is not None:
            key = (pos.cohort_id, pos.decision_provider, pos.symbol)
            self._cohort_symbol_map.pop(key, None)

    def _update_mae_mfe(self, pos: PaperPosition, current_price: float) -> None:
        """Update Maximum Adverse Excursion and Maximum Favorable Excursion in bps."""
        if pos.entry_price <= 0:
            return

        if pos.side == "LONG":
            delta_bps = ((current_price - pos.entry_price) / pos.entry_price) * 10_000.0
        elif pos.side == "SHORT":
            delta_bps = ((pos.entry_price - current_price) / pos.entry_price) * 10_000.0
        else:
            delta_bps = 0.0

        if delta_bps > 0:
            pos.mfe_bps = max(pos.mfe_bps, delta_bps)
        elif delta_bps < 0:
            pos.mae_bps = max(pos.mae_bps, abs(delta_bps))

    def _evaluate_tick_exit(
        self,
        pos: PaperPosition,
        T: int,
        p: float,
    ) -> Optional[ClosedTrade]:
        """
        Evaluate SL, TP, Horizon chronologically against trade tick (T, p).

        Invariants (Inclusive TP/SL):
        - LONG: p <= sl => SL; p >= tp => TP.
        - SHORT: p >= sl => SL; p <= tp => TP.
        - Gap jumps beyond SL/TP execute on the observable price p with adverse slippage;
          marked with data_gap=True without inventing fills at exact level.
        - Horizon reached at T >= horizon_deadline_ms.
        """
        sl = pos.stop_loss
        tp = pos.take_profit

        sl_hit = False
        tp_hit = False

        if pos.side == "LONG":
            if sl is not None and p <= sl:
                sl_hit = True
            if tp is not None and p >= tp:  # Inclusive
                tp_hit = True
        elif pos.side == "SHORT":
            if sl is not None and p >= sl:
                sl_hit = True
            if tp is not None and p <= tp:  # Inclusive
                tp_hit = True

        if sl_hit:
            # Check gap jump beyond SL
            is_gap = False
            if pos.side == "LONG" and sl is not None and p < sl:
                is_gap = True
            elif pos.side == "SHORT" and sl is not None and p > sl:
                is_gap = True

            if is_gap:
                pos.data_gap = True

            return self._close_trade_at_market(
                pos=pos,
                exit_reason="STOP_LOSS",
                raw_exit_price=p,
                exit_ts_ms=T,
            )

        if tp_hit:
            # Check gap jump beyond TP
            is_gap = False
            if pos.side == "LONG" and tp is not None and p > tp:
                is_gap = True
            elif pos.side == "SHORT" and tp is not None and p < tp:
                is_gap = True

            if is_gap:
                pos.data_gap = True

            return self._close_trade_at_market(
                pos=pos,
                exit_reason="TAKE_PROFIT",
                raw_exit_price=p,  # Executed at observable tick price p
                exit_ts_ms=T,
                is_maker=self.config.tp_is_maker if not is_gap else False,
            )

        # Horizon expiry check: first tick where T >= deadline
        if T >= pos.horizon_deadline_ms:
            return self._close_trade_at_market(
                pos=pos,
                exit_reason="HORIZON_EXPIRY",
                raw_exit_price=p,
                exit_ts_ms=T,
            )

        return None

    def _close_trade_at_market(
        self,
        pos: PaperPosition,
        exit_reason: Any,
        raw_exit_price: float,
        exit_ts_ms: int,
        is_maker: bool = False,
    ) -> ClosedTrade:
        """Close trade with adverse slippage at observable market price."""
        (
            exit_price,
            exit_notional_usdt,
            exit_fee_usdt,
            exit_slippage_usdt,
        ) = self.cost_model.calculate_exit_fill(
            side=pos.side,
            exit_reason=exit_reason,
            raw_price=raw_exit_price,
            quantity=pos.quantity,
            is_maker=is_maker,
        )

        pnl: PnLBreakdown = self.cost_model.calculate_trade_pnl(
            side=pos.side,
            raw_entry_price=pos.entry_price,
            raw_exit_price=raw_exit_price,
            quantity=pos.quantity,
            notional_usdt=pos.notional_usdt,
            entry_fee_usdt=pos.entry_fee_usdt,
            exit_fee_usdt=exit_fee_usdt,
            entry_slippage_usdt=pos.entry_slippage_usdt,
            exit_slippage_usdt=exit_slippage_usdt,
            opened_ts_ms=pos.opened_ts_ms,
            closed_ts_ms=exit_ts_ms,
            stop_loss=pos.stop_loss,
            funding_rate=pos.funding_rate_at_decision,
        )

        return ClosedTrade(
            trade_id=f"tr_{pos.position_id}",
            decision_id=pos.decision_id,
            cohort_id=pos.cohort_id,
            decision_provider=pos.decision_provider,
            symbol=pos.symbol,
            side=pos.side,
            entry_price=pos.entry_price,
            exit_price=exit_price,
            quantity=pos.quantity,
            notional_usdt=pos.notional_usdt,
            opened_ts_ms=pos.opened_ts_ms,
            closed_ts_ms=exit_ts_ms,
            exit_reason=exit_reason,
            trade_direction_profitable=pnl.trade_direction_profitable,
            prediction_direction_correct=pnl.prediction_direction_correct,
            trade_win=pnl.trade_win,
            gross_pnl_bps=pnl.gross_pnl_bps,
            net_pnl_bps=pnl.net_pnl_bps,
            fees_bps=pnl.fees_bps,
            slippage_bps=pnl.slippage_bps,
            funding_bps=pnl.funding_bps,
            gross_pnl_usdt=pnl.gross_pnl_usdt,
            fees_usdt=pnl.fees_usdt,
            slippage_usdt=pnl.slippage_usdt,
            funding_usdt=pnl.funding_usdt,
            net_pnl_usdt=pnl.net_pnl_usdt,
            pnl_R=pnl.pnl_R,
            costs_complete=pnl.costs_complete,
            data_gap=pos.data_gap,
            mae_bps=pos.mae_bps,
            mfe_bps=pos.mfe_bps,
            ticks_count=pos.ticks_processed,
            direction_correct=pnl.trade_direction_profitable,
            context=pos.context,
        )
