"""
Stub type definitions for fredapi module.
This file helps Pylance recognize the fredapi module.
"""
from typing import Any, Optional

class Fred:
    def __init__(self, api_key: str): ...
    def get_series(self, series_id: str, observation_start: Optional[str] = None, observation_end: Optional[str] = None, frequency: Optional[str] = None, aggregation_method: Optional[str] = None, output_type: Optional[int] = None, vintage_dates: Optional[str] = None) -> Any: ...
    def get_series_all_releases(self, series_id: str) -> Any: ...
    def get_series_as_of(self, series_id: str, release_date: str) -> Any: ...
    def get_series_vintage_dates(self, series_id: str) -> Any: ...
    def search(self, text: str, limit: Optional[int] = None, order_by: Optional[str] = None, sort_order: Optional[str] = None) -> Any: ...
    def get_category(self, category_id: int) -> Any: ...
    def get_category_children(self, category_id: int) -> Any: ...
    def get_category_related(self, category_id: int) -> Any: ...
    def get_group(self, group_id: str) -> Any: ...
    def get_sources(self) -> Any: ...
    def get_source(self, source_id: int) -> Any: ...
    def get_releases(self) -> Any: ...
    def get_release(self, release_id: int) -> Any: ...
    def get_release_dates(self, release_id: int) -> Any: ...
    def get_release_series(self, release_id: int) -> Any: ...
    def get_tags(self, series_id: Optional[str] = None, tag_names: Optional[str] = None, order_by: Optional[str] = None, sort_order: Optional[str] = None) -> Any: ...
    def get_related_tags(self, series_id: Optional[str] = None, tag_names: Optional[str] = None, exclude_tag_names: Optional[str] = None, order_by: Optional[str] = None, sort_order: Optional[str] = None) -> Any: ...
    def get_series_info(self, series_id: str) -> Any: ...
